### ISSUE TITLE
uaa scope

### ISSUE THREAD

**Issue by alexvasseur** [azwickey-pivotal/bosh-spectacle#1]
Could you detail what uaa scope is required, or which built-in PCF credential account should this app use in the manifest.yml ?
 env:
    bosh.director.clientId: xxxx
    bosh.director.ip: xxxx
    bosh.director.secret: xxxx

**Comment by adamzwickey** [comment]
I've only tested with the ops_manager client which has the bosh.admin scope.  Unfortunately the BOSH api docs don't state what specific scope is required for each API call

**Comment by alexvasseur** [comment]
is it from uaac targetting OpsManager and looking at contexts, or is it found into OpsManager / Director tile / credentials list - or is it just the "admin" password from OpsManager that goes into "secret" with "clientId"=ops_manager then?

**Comment by adamzwickey** [comment]
You'll want to log into your director VM and get a clientId + secret that is configured in this file:
/var/vcap/jobs/uaa/config/uaa.yml

**Comment by alexvasseur** [comment]
thank you
