### ISSUE TITLE
not working offline

### ISSUE THREAD

**Issue by alexvasseur** [azwickey-pivotal/bosh-spectacle#2]
index.html refers to jquery, bootstrap and d3 on the internet
this does not work on offline ops env

I can do a PR with npm install ...@version and a modified index.html --- but the offline javascript is ugly
with 
326 directories, 1850 files

and I am not sure how to trim this to just what's needed.

**Comment by adamzwickey** [comment]
Give it a try right now.  I just updated to include those in the jar in the static/libs folder.  Seems to work for me

**Comment by asehra** [comment]
You should be able to close this issue. I have validated offline access.

**Comment by alexvasseur** [comment]
great.
